.PHONY: clean All

All:
	@echo "----------Building project:[ JohnnyEngine - Debug ]----------"
	@"$(MAKE)" -f  "JohnnyEngine.mk"
	@echo "----------Building project:[ JohnnyEngine-Template - Debug ]----------"
	@"$(MAKE)" -f  "JohnnyEngine-Template.mk"
clean:
	@echo "----------Cleaning project:[ JohnnyEngine - Debug ]----------"
	@"$(MAKE)" -f  "JohnnyEngine.mk"  clean
	@echo "----------Cleaning project:[ JohnnyEngine-Template - Debug ]----------"
	@"$(MAKE)" -f  "JohnnyEngine-Template.mk" clean
