.PHONY: clean All

All:
	@echo "----------Building project:[ CubeWaves - Release ]----------"
	@cd "CubeWaves" && "$(MAKE)" -f  "CubeWaves.mk"
clean:
	@echo "----------Cleaning project:[ CubeWaves - Release ]----------"
	@cd "CubeWaves" && "$(MAKE)" -f  "CubeWaves.mk" clean
